export const FETCHED_SUCCESS_STOLEN_BIKES = "FETCHED_SUCCESS_STOLEN_BIKES";
export const FETCHED_ERROR_STOLEN_BIKES = "FETCHED_ERROR_STOLEN_BIKES";
export const FETCHED_LOADING_STOLEN_BIKES = "FETCHED_LOADING_STOLEN_BIKES";
